In [ ]:
Numpy uses arrays.
all elements in arrays should have same data type. 


In [1]:
import numpy as nd
#create an array
my_array = nd.array([1,10,20,40,50,45,34])
#print array in the same way
print(my_array)
#get type in the same way
print(type(my_array))
#do slicing in the same way
print(my_array[1:3])

[ 1 10 20 40 50 45 34]
<class 'numpy.ndarray'>
[10 20]


In [2]:
#find data type. Data type is the type of data included in the array.
print(my_array.dtype)

int32


In [4]:
#update: Similar to list.
my_array[2] = 200
print(my_array)

[  1  10 200  40  50  45  34]


In [5]:
#Multidimensional Arrays: Similar to list.
my_array_2 = nd.array([ [1,2,3,4,5], [11,12,13,14,15],[21,22,23,24,25]])
print(my_array_2)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [7]:
print(my_array_2[0,1])

2


In [10]:
#slicing
print(my_array_2[0:2, 1:3])

[[ 2  3]
 [12 13]]


In [12]:
#finding shape of arrays. 
print(my_array_2.shape)

(3, 5)


In [13]:
#how to do reshape
print(my_array_2.reshape(5,3))

[[ 1  2  3]
 [ 4  5 11]
 [12 13 14]
 [15 21 22]
 [23 24 25]]


In [14]:
print(my_array_2 <20)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]


In [16]:
print(my_array_2[my_array_2 <20])

[ 1  2  3  4  5 11 12 13 14 15]


In [17]:
#make an array from 1 till 100
arr2 = nd.arange(1,101)
print(arr2)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
